### ISSUE TITLE
Speed, Volume, and Pitch sliders are broken

### ISSUE THREAD

**Issue by NetworkJack2** [Shadowsith/qpicospeaker#5]
I am not sure why you thought rolling your own was a good idea, as they are now broken.

I am running latest patchlevel of Arch Linux.

The pitch slider controls the volume, and volumne and speed do absolutely nothing.

Just make this easier on everyone and just use normal slider controls:

$ pacman -Q qpicospeaker-git 
qpicospeaker-git r60.7429077-1
$ pacman -Q qt5-base 
qt5-base 5.14.1-4
$ pacman -Q qt5-multimedia
qt5-multimedia 5.14.1-1

**Comment by salazarbarrera** [comment]
I know I'm a year late, but at least for me, this was fixed by the [patch-3 made by Reyoking](https://github.com/Reyoking/qpicospeaker/tree/patch-3). In other words, the pull request #6 .
